version: "3.3"

services:
  events_f:
    build: 
      context: .
      dockerfile: /build/Dockerfile.test
    image: events_f
    volumes:
      - ".:/usr/src"
      - "/usr/src/node_modules"
      - "/usr/src/.angular"
    command: ng build --configuration testing
