version: "3.8"

services:
  events_f:
    build: 
      context: .
      dockerfile: Dockerfile
    image: events_f
    container_name: events_f
    ports:
      - "4200:4200"

    volumes:
      - ".:/usr/src"
      - "/usr/src/node_modules"
      - "/usr/src/.angular"
    command: ng serve --disable-host-check=false --poll 2000 --host 0.0.0.0 --port 4200 
    